# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vlad1819/C++/cplusplus

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vlad1819/C++/cplusplus

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vlad1819/C++/cplusplus/CMakeFiles /home/vlad1819/C++/cplusplus/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vlad1819/C++/cplusplus/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pool_test

# Build rule for target.
pool_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pool_test
.PHONY : pool_test

# fast build rule for target.
pool_test/fast:
	$(MAKE) -f CMakeFiles/pool_test.dir/build.make CMakeFiles/pool_test.dir/build
.PHONY : pool_test/fast

#=============================================================================
# Target rules for targets named process_exec

# Build rule for target.
process_exec: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 process_exec
.PHONY : process_exec

# fast build rule for target.
process_exec/fast:
	$(MAKE) -f CMakeFiles/process_exec.dir/build.make CMakeFiles/process_exec.dir/build
.PHONY : process_exec/fast

#=============================================================================
# Target rules for targets named process_simple

# Build rule for target.
process_simple: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 process_simple
.PHONY : process_simple

# fast build rule for target.
process_simple/fast:
	$(MAKE) -f CMakeFiles/process_simple.dir/build.make CMakeFiles/process_simple.dir/build
.PHONY : process_simple/fast

#=============================================================================
# Target rules for targets named test_move

# Build rule for target.
test_move: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_move
.PHONY : test_move

# fast build rule for target.
test_move/fast:
	$(MAKE) -f CMakeFiles/test_move.dir/build.make CMakeFiles/test_move.dir/build
.PHONY : test_move/fast

#=============================================================================
# Target rules for targets named PosixSocketClientTest

# Build rule for target.
PosixSocketClientTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PosixSocketClientTest
.PHONY : PosixSocketClientTest

# fast build rule for target.
PosixSocketClientTest/fast:
	$(MAKE) -f IBJts/source/PosixClient/CMakeFiles/PosixSocketClientTest.dir/build.make IBJts/source/PosixClient/CMakeFiles/PosixSocketClientTest.dir/build
.PHONY : PosixSocketClientTest/fast

pool.o: pool.cpp.o
.PHONY : pool.o

# target to build an object file
pool.cpp.o:
	$(MAKE) -f CMakeFiles/pool_test.dir/build.make CMakeFiles/pool_test.dir/pool.cpp.o
.PHONY : pool.cpp.o

pool.i: pool.cpp.i
.PHONY : pool.i

# target to preprocess a source file
pool.cpp.i:
	$(MAKE) -f CMakeFiles/pool_test.dir/build.make CMakeFiles/pool_test.dir/pool.cpp.i
.PHONY : pool.cpp.i

pool.s: pool.cpp.s
.PHONY : pool.s

# target to generate assembly for a file
pool.cpp.s:
	$(MAKE) -f CMakeFiles/pool_test.dir/build.make CMakeFiles/pool_test.dir/pool.cpp.s
.PHONY : pool.cpp.s

process_exec.o: process_exec.cpp.o
.PHONY : process_exec.o

# target to build an object file
process_exec.cpp.o:
	$(MAKE) -f CMakeFiles/process_exec.dir/build.make CMakeFiles/process_exec.dir/process_exec.cpp.o
.PHONY : process_exec.cpp.o

process_exec.i: process_exec.cpp.i
.PHONY : process_exec.i

# target to preprocess a source file
process_exec.cpp.i:
	$(MAKE) -f CMakeFiles/process_exec.dir/build.make CMakeFiles/process_exec.dir/process_exec.cpp.i
.PHONY : process_exec.cpp.i

process_exec.s: process_exec.cpp.s
.PHONY : process_exec.s

# target to generate assembly for a file
process_exec.cpp.s:
	$(MAKE) -f CMakeFiles/process_exec.dir/build.make CMakeFiles/process_exec.dir/process_exec.cpp.s
.PHONY : process_exec.cpp.s

process_simple.o: process_simple.cpp.o
.PHONY : process_simple.o

# target to build an object file
process_simple.cpp.o:
	$(MAKE) -f CMakeFiles/process_simple.dir/build.make CMakeFiles/process_simple.dir/process_simple.cpp.o
.PHONY : process_simple.cpp.o

process_simple.i: process_simple.cpp.i
.PHONY : process_simple.i

# target to preprocess a source file
process_simple.cpp.i:
	$(MAKE) -f CMakeFiles/process_simple.dir/build.make CMakeFiles/process_simple.dir/process_simple.cpp.i
.PHONY : process_simple.cpp.i

process_simple.s: process_simple.cpp.s
.PHONY : process_simple.s

# target to generate assembly for a file
process_simple.cpp.s:
	$(MAKE) -f CMakeFiles/process_simple.dir/build.make CMakeFiles/process_simple.dir/process_simple.cpp.s
.PHONY : process_simple.cpp.s

test_move.o: test_move.cpp.o
.PHONY : test_move.o

# target to build an object file
test_move.cpp.o:
	$(MAKE) -f CMakeFiles/test_move.dir/build.make CMakeFiles/test_move.dir/test_move.cpp.o
.PHONY : test_move.cpp.o

test_move.i: test_move.cpp.i
.PHONY : test_move.i

# target to preprocess a source file
test_move.cpp.i:
	$(MAKE) -f CMakeFiles/test_move.dir/build.make CMakeFiles/test_move.dir/test_move.cpp.i
.PHONY : test_move.cpp.i

test_move.s: test_move.cpp.s
.PHONY : test_move.s

# target to generate assembly for a file
test_move.cpp.s:
	$(MAKE) -f CMakeFiles/test_move.dir/build.make CMakeFiles/test_move.dir/test_move.cpp.s
.PHONY : test_move.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... process_exec"
	@echo "... pool_test"
	@echo "... test_move"
	@echo "... process_simple"
	@echo "... PosixSocketClientTest"
	@echo "... pool.o"
	@echo "... pool.i"
	@echo "... pool.s"
	@echo "... process_exec.o"
	@echo "... process_exec.i"
	@echo "... process_exec.s"
	@echo "... process_simple.o"
	@echo "... process_simple.i"
	@echo "... process_simple.s"
	@echo "... test_move.o"
	@echo "... test_move.i"
	@echo "... test_move.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

